backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: img

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Index Page
        name: index
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: index
      - file: src/pages/about.md
        label: About Page
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about
      - file: src/pages/services.md
        label: Services Page
        name: services
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: services
      - file: src/pages/testimonials.md
        label: Testimonials Page
        name: testimonials
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: testimonials
      - file: src/pages/contact.md
        label: Contact Page
        name: contact
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: contact
